### ISSUE TITLE
NAs are automatically converted to 0. I don't want that. 

### ISSUE THREAD

**Issue by adhikariraju1** [adhikariraju1/MPP_Thesis_Adhikari#1]
library(bea.R)
beaKey <- 'C3812F4D-F498-40F8-9F36-9FF5AF65DBD7'

beaPop <- list(
    'UserID' = beaKey ,
    'Method' = 'GetData',
    'datasetname' = 'RegionalIncome',
    'TableName' = 'CA1' ,
    'LineCode' = '2',
    'Year' = '1992, 1996, 2000, 2004, 2008, 2012' ,
    'GeoFips' = 'COUNTY' ,
    'ResultFormat' = 'json'
);
beaPop <- beaGet(beaPop)

**Comment by devvartpoddar** [comment]
@devvartpoddar
