### ISSUE TITLE
Merging and Separating

### ISSUE THREAD

**Issue by adhikariraju1** [adhikariraju1/MPP_Thesis_Adhikari#3]
@devvartpoddar 
Please see the #TOTO under Statistics.Rmd

Thanks :-)

**Comment by devvartpoddar** [comment]
Naah :). But small question. Have you pushed the new changes to the repo? I see the last commit as 3 hours old?

**Comment by adhikariraju1** [comment]
yes just did. sorry.

**Comment by adhikariraju1** [comment]
@devvartpoddar the filter function worked in the bea_df that you helped solve. However, when i try the same function with the unemployment_df, it doesn't work. I am trying to remove all the states that say "AK" or "PR" from unemployment_df since I do not have election data for Alaska and Puerto Rico. See #TOTO.
